normalize: null

encoder: whisper
encoder_conf:
    whisper_model: small
    dropout_rate: 0.0
    # do_pad_trim: true         # should be set when doing zero-shot inference

decoder: whisper
decoder_conf:
    whisper_model: small
    dropout_rate: 0.0

preprocessor: default
preprocessor_conf:
    whisper_language: "zh"
    whisper_task: "transcribe"

model_conf:
    ctc_weight: 0.0
    lsm_weight: 0.1
    length_normalized_loss: false
    extract_feats_in_collect_stats: false
    sym_sos: "<|startoftranscript|>"
    sym_eos: "<|endoftext|>"

frontend: null
input_size: 1                   # to prevent build_model() from complaining

seed: 2022
log_interval: 100
num_att_plot: 0
num_workers: 4
sort_in_batch: descending       # how to sort data in making batch
sort_batch: descending          # how to sort created batches
batch_type: folded
batch_size: 12
accum_grad: 1
max_epoch: 7
patience: none
init: none
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 3

use_amp: true
cudnn_deterministic: false
cudnn_benchmark: false

optim: adamw
grad_clip: 1.0
optim_conf:
    lr: 5.0e-04
    weight_decay: 0.01
    betas:
    - 0.9
    - 0.99
    eps: 1.0e-06
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 1500


# LoRA finetune related
use_adapter: true
adapter: gora
save_strategy: required_grad_only
adapter_conf:
    rank: 48  #8
    alpha: 96    #16
    dropout_rate: 0.05
    target_modules: ["query", "key", "value", "attn.out","mlp.0", "mlp.2"]

# ========== GoRA 新增配置 ==========
gora_total_param_budget: 6488064  # 你的模型总可训练参数量（6.49M）
gora_grad_steps: 4           # 梯度累积步数
gora_min_rank: 4             # 每层最小秩
gora_max_rank: 32            # 每层最大秩
gora_importance_type: "union_mean"  # 重要性计算方式
gora_stable_gamma: 1.0      # 初始化稳定系数
gora_init_method: "grad_compress"   # GoRA初始化方式
gora_rank_stablize: true     # 秩稳定化